name: Build excluded packages

on: pull_request

jobs:
  build:
    name: Build excluded packages
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN_VERSION: nightly-2021-07-21
      CARGO_INCREMENTAL: 0
    steps:
#      - name: Cancel Previous Runs
#        uses: styfle/cancel-workflow-action@0.9.0
#        with:
#          access_token: ${{ github.token }}
#
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Print toolchain version
        run: echo running with "$RUST_TOOLCHAIN_VERSION"

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          override: true
          components: rustfmt, clippy

      - name: Read excluded packages from Cargo.toml
        id: read_excluded
        uses: SebRollen/toml-action@v1.0.0
        with:
          file: 'Cargo.toml'
          field: 'workspace.exclude'

      - name: Build excluded packages
        run: |
          for i in "${${{ steps.read_excluded.outputs.value }}[@]}"
          do
             echo "$i"
          done
