name: Build excluded packages

on: pull_request

jobs:
  build:
    name: Build excluded packages
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN_VERSION: nightly-2021-07-21
      CARGO_INCREMENTAL: 0
    steps:
#      - name: Cancel Previous Runs
#        uses: styfle/cancel-workflow-action@0.9.0
#        with:
#          access_token: ${{ github.token }}
#
      - name: Checkout Source code
        uses: actions/checkout@v2

      - name: Print Toolchain Version
        run: echo running with "$RUST_TOOLCHAIN_VERSION"

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          override: true
          components: rustfmt, clippy

      - name: halo
        run: less Cargo.toml

      - name: Read excluded packages from Cargo.toml
        id: read_excluded
        uses: SebRollen/toml-action@v1.0.0
        with:
          file: 'Cargo.toml'
          field: exclude

      - name: Print
        run: echo ${{ steps.read_excluded.VALUE }} && echo ${{ steps.read_excluded.ouptuts.VALUE }} && echo ${{ steps.read_excluded.value }} && echo ${{ steps.read_excluded.outputs.value }}

      - name: Print2
        env:
          TEMP: ${{ steps.read_excluded.outputs.value }}
        run: echo ${{ steps.read_excluded.outputs }} && echo ${{ steps.read_excluded.outputs.value }} && echo $TEMP
